ALTER TABLE "profile_enrollment_data" DROP COLUMN "gender";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "civil_status";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "monthly_income";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "work_type";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "company_org_name";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "preferred_learning_hub";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "student_type";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "sub_student_type";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "student_status";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "religion";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "strand";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "last_school_attended";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "term_applied";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "program_focus";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "program_applied";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "certification_field";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "is_leap_pad_re_enrollment";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "is_self_enrolled";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "permanent_address_country";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "permanent_address_line1";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "permanent_address_line2";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "permanent_address_province";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "permanent_address_city";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "permanent_address_barangay";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "permanent_address_zip_code";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "interested_in_scholarship";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "with_medical_condition";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "lost_date";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "lost_reason";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "lost_reason_specific";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "lost_reason_remark";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "profile_locked_date";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "subscription_expiration_date";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "father_status";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "mother_status";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_type";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_given_name";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_family_name";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_suffix";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_birthdate";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_mobile";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_email";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_occupation";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "guardian_relationship";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "copy_guardian_address";--> statement-breakpoint
ALTER TABLE "profile_enrollment_data" DROP COLUMN "copy_permanent_guardian_address";