include:
  - path: services/pgdog-postgres/compose.yml
    env_file: services/pgdog-postgres/.env
  - path: services/inngest/compose.yml
    env_file: services/inngest/.env
  - path: services/pgadmin/compose.yml
    env_file: services/pgadmin/.env
