export const profileFixtures = [
  {
    id: "3591b2d2-886b-45c6-bcbd-3c8756b40101",
    name: "Ari Santos",
    middleName: null,
    email: "ari.santos@example.edu",
    flowType: "bachelors" as const,
    status: "validated" as const,
    formOverrides: {
      givenName: "Ari",
      familyName: "Santos",
      birthplace: "Quezon City",
      birthdate: "2003-04-18",
      mobile: "09171234567",
      withMedicalCondition: "No",
      interestedForAScholarship: "Yes",
    },
  },
  {
    id: "3591b2d2-886b-45c6-bcbd-3c8756b40102",
    name: "Mika Reyes",
    middleName: null,
    email: "mika.reyes@example.edu",
    flowType: "bachelors" as const,
    status: "new" as const,
    formOverrides: {
      givenName: "Mika",
      familyName: "Reyes",
      birthplace: "Pasig City",
      birthdate: "2002-09-07",
      mobile: "09181234567",
      withMedicalCondition: "Yes",
      medicalDiagnosisDescription: "Managed asthma",
      interestedForAScholarship: "No",
    },
  },
  {
    id: "3591b2d2-886b-45c6-bcbd-3c8756b40103",
    name: "Noel Cruz",
    middleName: null,
    email: "noel.cruz@example.edu",
    flowType: "bachelors" as const,
    status: "guidance_needed" as const,
    formOverrides: {
      givenName: "Noel",
      familyName: "Cruz",
      birthplace: "Antipolo City",
      birthdate: "2004-01-22",
      mobile: "09191234567",
      withMedicalCondition: "No",
      interestedForAScholarship: "No",
    },
  },
  {
    id: "3591b2d2-886b-45c6-bcbd-3c8756b40104",
    name: "Sam Lim",
    middleName: null,
    email: "sam.lim@example.edu",
    flowType: "bachelors" as const,
    status: "completed" as const,
    formOverrides: {
      givenName: "Sam",
      familyName: "Lim",
      birthplace: "Manila",
      birthdate: "2001-12-03",
      mobile: "09201234567",
    },
  },
  {
    id: "3591b2d2-886b-45c6-bcbd-3c8756b40105",
    name: "Rosa Cruz",
    middleName: null,
    email: "rosa.cruz@example.edu",
    flowType: "microcredentials" as const,
    status: "new" as const,
    formOverrides: {
      givenName: "Rosa",
      familyName: "Cruz",
      birthplace: "Makati City",
      birthdate: "1998-06-14",
      mobile: "09211234567",
    },
  },
] as const;
