[general]
host = "0.0.0.0"
port = 6432
pub_sub_channel_size = 4096

[[databases]]
name = "mihc"
host = "app-postgres"
port = 5432

[[databases]]
name = "mihc-test"
host = "app-postgres"
port = 5432

[[databases]]
name = "postgres"
host = "app-postgres"
port = 5432
